"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 08:42:39.569972
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agentrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("llm_calls", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agentrun", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agentrun_cycle_id"), ["cycle_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agentrun_task_id"), ["task_id"], unique=False)

    op.create_table(
        "alert",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alert_workspace"), ["workspace"], unique=False)

    op.create_table(
        "approval",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("draft_id", sa.Integer(), nullable=False),
        sa.Column("decision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reviewer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("diff", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_draft_id"), ["draft_id"], unique=False)

    op.create_table(
        "approvaltokenuse",
        sa.Column("nonce", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("used_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("approved_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("nonce"),
    )
    op.create_table(
        "brainversion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("changed_fields", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("brainversion", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_brainversion_workspace"), ["workspace"], unique=False)

    op.create_table(
        "calendaritem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("draft_id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scheduled_for", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("published_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("published_via", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metrics_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("calendaritem", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calendaritem_cycle_id"), ["cycle_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_calendaritem_draft_id"), ["draft_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_calendaritem_workspace"), ["workspace"], unique=False)

    op.create_table(
        "changedecision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("learnings_id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("change_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("decision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("changedecision", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_changedecision_cycle_id"), ["cycle_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_changedecision_learnings_id"), ["learnings_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_changedecision_workspace"), ["workspace"], unique=False
        )

    op.create_table(
        "connectorcredential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("settings", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scopes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("connected_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("connectorcredential", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_connectorcredential_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_connectorcredential_workspace"), ["workspace"], unique=False
        )

    op.create_table(
        "contentrevision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("piece_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("angle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("min_score", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("scores", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contentrevision", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contentrevision_piece_id"), ["piece_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_contentrevision_workspace"), ["workspace"], unique=False
        )

    op.create_table(
        "creative",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("draft_id", sa.Integer(), nullable=False),
        sa.Column("text_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slots", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scores", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fixes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("checks", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.Column("image_meta", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creative", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_creative_draft_id"), ["draft_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_creative_workspace"), ["workspace"], unique=False)

    op.create_table(
        "crmsnapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("taken_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("new_contacts", sa.Integer(), nullable=False),
        sa.Column("open_deals", sa.Integer(), nullable=False),
        sa.Column("pipeline_value", sa.Float(), nullable=False),
        sa.Column("won_deals", sa.Integer(), nullable=False),
        sa.Column("won_value", sa.Float(), nullable=False),
        sa.Column("contacts_by_source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("crmsnapshot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crmsnapshot_taken_at"), ["taken_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_crmsnapshot_workspace"), ["workspace"], unique=False)

    op.create_table(
        "cycle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("week_start", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("halted_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cycle", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cycle_workspace"), ["workspace"], unique=False)

    op.create_table(
        "draft",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("piece_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("angle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("original_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("min_score", sa.Integer(), nullable=False),
        sa.Column("passed_critic", sa.Boolean(), nullable=False),
        sa.Column("history_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("strategy_version", sa.Integer(), nullable=False),
        sa.Column("memory_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("draft", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_draft_cycle_id"), ["cycle_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_draft_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_draft_workspace"), ["workspace"], unique=False)

    op.create_table(
        "editpattern",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rule", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("editpattern", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_editpattern_workspace"), ["workspace"], unique=False)

    op.create_table(
        "experimentregistration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("experiment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verdict", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("experimentregistration", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_experimentregistration_cycle_id"), ["cycle_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_experimentregistration_workspace"), ["workspace"], unique=False
        )

    op.create_table(
        "guardrailblock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("piece_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rule", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.Column("excerpt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guardrailblock", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guardrailblock_workspace"), ["workspace"], unique=False
        )

    op.create_table(
        "keywordrank",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("keyword", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("clicks", sa.Float(), nullable=False),
        sa.Column("impressions", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("keywordrank", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_keywordrank_keyword"), ["keyword"], unique=False)
        batch_op.create_index(batch_op.f("ix_keywordrank_workspace"), ["workspace"], unique=False)

    op.create_table(
        "learnings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("learnings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_learnings_workspace"), ["workspace"], unique=False)

    op.create_table(
        "llmcall",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("stop_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("span_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llmcall", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llmcall_agent"), ["agent"], unique=False)
        batch_op.create_index(batch_op.f("ix_llmcall_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_llmcall_tag"), ["tag"], unique=False)
        batch_op.create_index(batch_op.f("ix_llmcall_trace_id"), ["trace_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llmcall_workspace"), ["workspace"], unique=False)

    op.create_table(
        "memorypiece",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("draft_id", sa.Integer(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("published_on", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pillar", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("angle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("persona", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hypothesis", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metric", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trials", sa.Integer(), nullable=False),
        sa.Column("successes", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("features", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("strategy_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memorypiece", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_memorypiece_content_type"), ["content_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memorypiece_draft_id"), ["draft_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_memorypiece_workspace"), ["workspace"], unique=False)

    op.create_table(
        "onboardingjob",
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("workspace"),
    )
    op.create_table(
        "pagesnapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("competitor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fetched_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("links", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pagesnapshot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pagesnapshot_url"), ["url"], unique=False)
        batch_op.create_index(batch_op.f("ix_pagesnapshot_workspace"), ["workspace"], unique=False)

    op.create_table(
        "panelrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("experiment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("responses", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prediction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recommendation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trust", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("panelrun", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_panelrun_cycle_id"), ["cycle_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_panelrun_experiment"), ["experiment"], unique=False)
        batch_op.create_index(batch_op.f("ix_panelrun_workspace"), ["workspace"], unique=False)

    op.create_table(
        "performancerow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("draft_id", sa.Integer(), nullable=True),
        sa.Column("impressions", sa.Float(), nullable=False),
        sa.Column("clicks", sa.Float(), nullable=False),
        sa.Column("engagements", sa.Float(), nullable=False),
        sa.Column("sessions", sa.Float(), nullable=False),
        sa.Column("conversions", sa.Float(), nullable=False),
        sa.Column("sends", sa.Float(), nullable=False),
        sa.Column("opens", sa.Float(), nullable=False),
        sa.Column("replies", sa.Float(), nullable=False),
        sa.Column("unsubscribes", sa.Float(), nullable=False),
        sa.Column("spend", sa.Float(), nullable=False),
        sa.Column("uploaded_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("performancerow", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_performancerow_draft_id"), ["draft_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_performancerow_workspace"), ["workspace"], unique=False
        )

    op.create_table(
        "persona",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("profile", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("support", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("persona", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_persona_generation"), ["generation"], unique=False)
        batch_op.create_index(batch_op.f("ix_persona_workspace"), ["workspace"], unique=False)

    op.create_table(
        "playbookrule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("feature", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("statement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lift_pct", sa.Float(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("pieces_with", sa.Integer(), nullable=False),
        sa.Column("pieces_without", sa.Integer(), nullable=False),
        sa.Column("found_on", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_on", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("held_runs", sa.Integer(), nullable=False),
        sa.Column("failed_runs", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("playbookrule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_playbookrule_workspace"), ["workspace"], unique=False)

    op.create_table(
        "rolemodel",
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("role"),
    )
    op.create_table(
        "ruleevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lift_pct", sa.Float(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("pieces_with", sa.Integer(), nullable=False),
        sa.Column("pieces_without", sa.Integer(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ruleevent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ruleevent_rule_id"), ["rule_id"], unique=False)

    op.create_table(
        "seenitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_seen", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("seenitem", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seenitem_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_seenitem_workspace"), ["workspace"], unique=False)

    op.create_table(
        "signal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("monitor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("suggested_response", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sources", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_importance", sa.Float(), nullable=False),
        sa.Column("warning", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("decided_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("decided_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signal", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signal_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_signal_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_signal_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_signal_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_signal_workspace"), ["workspace"], unique=False)

    op.create_table(
        "span",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("span_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("ended_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attributes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("span", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_span_span_id"), ["span_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_span_trace_id"), ["trace_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_span_workspace"), ["workspace"], unique=False)

    op.create_table(
        "strategycomment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("section", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("strategycomment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_strategycomment_workspace"), ["workspace"], unique=False
        )

    op.create_table(
        "syncrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("finished_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("matched", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("syncrun", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_syncrun_started_at"), ["started_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_syncrun_workspace"), ["workspace"], unique=False)

    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("finished_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_cycle_id"), ["cycle_id"], unique=False)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspaces", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "workspacebudget",
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weekly_limit_usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("workspace"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspacebudget")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_cycle_id"))

    op.drop_table("task")
    with op.batch_alter_table("syncrun", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_syncrun_workspace"))
        batch_op.drop_index(batch_op.f("ix_syncrun_started_at"))

    op.drop_table("syncrun")
    with op.batch_alter_table("strategycomment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategycomment_workspace"))

    op.drop_table("strategycomment")
    with op.batch_alter_table("span", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_span_workspace"))
        batch_op.drop_index(batch_op.f("ix_span_trace_id"))
        batch_op.drop_index(batch_op.f("ix_span_span_id"))

    op.drop_table("span")
    with op.batch_alter_table("signal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signal_workspace"))
        batch_op.drop_index(batch_op.f("ix_signal_status"))
        batch_op.drop_index(batch_op.f("ix_signal_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_signal_created_at"))
        batch_op.drop_index(batch_op.f("ix_signal_category"))

    op.drop_table("signal")
    with op.batch_alter_table("seenitem", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seenitem_workspace"))
        batch_op.drop_index(batch_op.f("ix_seenitem_key"))

    op.drop_table("seenitem")
    with op.batch_alter_table("ruleevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ruleevent_rule_id"))

    op.drop_table("ruleevent")
    op.drop_table("rolemodel")
    with op.batch_alter_table("playbookrule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playbookrule_workspace"))

    op.drop_table("playbookrule")
    with op.batch_alter_table("persona", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_persona_workspace"))
        batch_op.drop_index(batch_op.f("ix_persona_generation"))

    op.drop_table("persona")
    with op.batch_alter_table("performancerow", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performancerow_workspace"))
        batch_op.drop_index(batch_op.f("ix_performancerow_draft_id"))

    op.drop_table("performancerow")
    with op.batch_alter_table("panelrun", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_panelrun_workspace"))
        batch_op.drop_index(batch_op.f("ix_panelrun_experiment"))
        batch_op.drop_index(batch_op.f("ix_panelrun_cycle_id"))

    op.drop_table("panelrun")
    with op.batch_alter_table("pagesnapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pagesnapshot_workspace"))
        batch_op.drop_index(batch_op.f("ix_pagesnapshot_url"))

    op.drop_table("pagesnapshot")
    op.drop_table("onboardingjob")
    with op.batch_alter_table("memorypiece", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memorypiece_workspace"))
        batch_op.drop_index(batch_op.f("ix_memorypiece_draft_id"))
        batch_op.drop_index(batch_op.f("ix_memorypiece_content_type"))

    op.drop_table("memorypiece")
    with op.batch_alter_table("llmcall", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llmcall_workspace"))
        batch_op.drop_index(batch_op.f("ix_llmcall_trace_id"))
        batch_op.drop_index(batch_op.f("ix_llmcall_tag"))
        batch_op.drop_index(batch_op.f("ix_llmcall_created_at"))
        batch_op.drop_index(batch_op.f("ix_llmcall_agent"))

    op.drop_table("llmcall")
    with op.batch_alter_table("learnings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learnings_workspace"))

    op.drop_table("learnings")
    with op.batch_alter_table("keywordrank", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_keywordrank_workspace"))
        batch_op.drop_index(batch_op.f("ix_keywordrank_keyword"))

    op.drop_table("keywordrank")
    with op.batch_alter_table("guardrailblock", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guardrailblock_workspace"))

    op.drop_table("guardrailblock")
    with op.batch_alter_table("experimentregistration", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experimentregistration_workspace"))
        batch_op.drop_index(batch_op.f("ix_experimentregistration_cycle_id"))

    op.drop_table("experimentregistration")
    with op.batch_alter_table("editpattern", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_editpattern_workspace"))

    op.drop_table("editpattern")
    with op.batch_alter_table("draft", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_draft_workspace"))
        batch_op.drop_index(batch_op.f("ix_draft_status"))
        batch_op.drop_index(batch_op.f("ix_draft_cycle_id"))

    op.drop_table("draft")
    with op.batch_alter_table("cycle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cycle_workspace"))

    op.drop_table("cycle")
    with op.batch_alter_table("crmsnapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crmsnapshot_workspace"))
        batch_op.drop_index(batch_op.f("ix_crmsnapshot_taken_at"))

    op.drop_table("crmsnapshot")
    with op.batch_alter_table("creative", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creative_workspace"))
        batch_op.drop_index(batch_op.f("ix_creative_draft_id"))

    op.drop_table("creative")
    with op.batch_alter_table("contentrevision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contentrevision_workspace"))
        batch_op.drop_index(batch_op.f("ix_contentrevision_piece_id"))

    op.drop_table("contentrevision")
    with op.batch_alter_table("connectorcredential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_connectorcredential_workspace"))
        batch_op.drop_index(batch_op.f("ix_connectorcredential_provider"))

    op.drop_table("connectorcredential")
    with op.batch_alter_table("changedecision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_changedecision_workspace"))
        batch_op.drop_index(batch_op.f("ix_changedecision_learnings_id"))
        batch_op.drop_index(batch_op.f("ix_changedecision_cycle_id"))

    op.drop_table("changedecision")
    with op.batch_alter_table("calendaritem", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendaritem_workspace"))
        batch_op.drop_index(batch_op.f("ix_calendaritem_draft_id"))
        batch_op.drop_index(batch_op.f("ix_calendaritem_cycle_id"))

    op.drop_table("calendaritem")
    with op.batch_alter_table("brainversion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_brainversion_workspace"))

    op.drop_table("brainversion")
    op.drop_table("approvaltokenuse")
    with op.batch_alter_table("approval", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_draft_id"))

    op.drop_table("approval")
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_workspace"))

    op.drop_table("alert")
    with op.batch_alter_table("agentrun", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agentrun_task_id"))
        batch_op.drop_index(batch_op.f("ix_agentrun_cycle_id"))

    op.drop_table("agentrun")
    # ### end Alembic commands ###
