"""jobs audit roles cache

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 08:52:49.729816
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prev_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auditlog", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auditlog_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_auditlog_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_auditlog_workspace"), ["workspace"], unique=False)

    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("lease_until", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("worker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("result", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_idempotency_key"), ["idempotency_key"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_job_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_lease_until"), ["lease_until"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_run_after"), ["run_after"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_workspace"), ["workspace"], unique=False)

    op.create_table(
        "llmcache",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("namespace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("llmcache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llmcache_namespace"), ["namespace"], unique=False)

    op.create_table(
        "systemflag",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("set_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("set_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("llmcall", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cached", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "roles", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="{}"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("roles")

    with op.batch_alter_table("llmcall", schema=None) as batch_op:
        batch_op.drop_column("cached")

    op.drop_table("systemflag")
    with op.batch_alter_table("llmcache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llmcache_namespace"))

    op.drop_table("llmcache")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_workspace"))
        batch_op.drop_index(batch_op.f("ix_job_status"))
        batch_op.drop_index(batch_op.f("ix_job_run_after"))
        batch_op.drop_index(batch_op.f("ix_job_lease_until"))
        batch_op.drop_index(batch_op.f("ix_job_kind"))
        batch_op.drop_index(batch_op.f("ix_job_idempotency_key"))

    op.drop_table("job")
    with op.batch_alter_table("auditlog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auditlog_workspace"))
        batch_op.drop_index(batch_op.f("ix_auditlog_at"))
        batch_op.drop_index(batch_op.f("ix_auditlog_action"))

    op.drop_table("auditlog")
    # ### end Alembic commands ###
