"""approval channels

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 09:01:22.125477
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channelidentity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("channelidentity", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_channelidentity_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_channelidentity_workspace"), ["workspace"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channelidentity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channelidentity_workspace"))
        batch_op.drop_index(batch_op.f("ix_channelidentity_external_id"))

    op.drop_table("channelidentity")
    # ### end Alembic commands ###
